import { useEffect, useMemo, useState, type FormEvent } from "react";
import { usePrivy } from "@privy-io/react-auth";
import { ArrowDownLeft, ArrowUpRight, ChevronDown, LogOut, Radio, WalletCards, Zap } from "lucide-react";
import toast from "react-hot-toast";
import { ASSET_NAMES, MARKETS, type Candle, type LeaderboardEntry, type MarketSymbol, type OrderView, type PortfolioView, type TradeView, type UserProfile } from "@kraftbase/shared";
import { cancelPendingOrder, DEMO, loadCandles, loadLeaderboard, loadMe, loadOrders, loadPortfolio, loadTrades, placeConditionalOrder, placeOrder, saveProfile } from "./api";
import { Chart } from "./Chart";
import { useMarket } from "./useMarket";
import { mergeTrade, uniqueTrades } from "./trades";

const money = (v: string | number, digits = 2) => Number(v).toLocaleString("en-US", { minimumFractionDigits: digits, maximumFractionDigits: digits });
const short = (symbol: string) => symbol.replace("USDT", "");

export function App() {
  const privy = usePrivy(); const demo = DEMO; const authenticated = demo || privy.authenticated;
  const [token, setToken] = useState<string>(); const [selected, setSelected] = useState<MarketSymbol>("BTCUSDT");
  const [portfolio, setPortfolio] = useState<PortfolioView>(); const [trades, setTrades] = useState<TradeView[]>([]); const [candles, setCandles] = useState<Candle[]>([]);
  const [orders, setOrders] = useState<OrderView[]>([]); const [leaders, setLeaders] = useState<LeaderboardEntry[]>([]);
  const [profile, setProfile] = useState<UserProfile>();
  useEffect(() => { if (!authenticated) { setToken(undefined); setProfile(undefined); return; } if (demo) setToken("demo-token"); else privy.getAccessToken().then(t => setToken(t ?? undefined)); }, [authenticated, demo]);
  useEffect(() => { if (!token) return; loadMe(token).then(result => setProfile(result.user)).catch(e => toast.error(e.message)); }, [token]);
  const refreshBonusData = () => { if (!token) return; Promise.all([loadOrders(token), loadLeaderboard(token)]).then(([o,l]) => { setOrders(o.orders); setLeaders(l.entries); }).catch(e => toast.error(e.message)); };
  useEffect(() => { if (!token || !profile?.profileComplete) return; Promise.all([loadPortfolio(token), loadTrades(token), loadOrders(token), loadLeaderboard(token)]).then(([p,t,o,l]) => { setPortfolio(p); setTrades(uniqueTrades(t.trades)); setOrders(o.orders); setLeaders(l.entries); }).catch(e => toast.error(e.message)); }, [token, profile?.profileComplete]);
  useEffect(() => { setCandles([]); loadCandles(selected).then(r => setCandles(r.candles)).catch(() => toast.error("Could not load chart history")); }, [selected]);
  const market = useMarket(profile?.profileComplete ? token : undefined, selected);
  useEffect(() => { if (!market.orderEvent) return; toast(market.orderEvent.message); refreshBonusData(); }, [market.orderEvent]);
  useEffect(() => { if (!market.executionEvent) return; setPortfolio(market.executionEvent.portfolio); setTrades(old => mergeTrade(old, market.executionEvent!.trade)); refreshBonusData(); }, [market.executionEvent]);
  useEffect(() => { const c = market.liveCandle; if (!c) return; setCandles(old => { const next = [...old], i = next.findIndex(x => x.time === c.time); if (i >= 0) next[i] = c; else next.push(c); return next.slice(-120); }); }, [market.liveCandle]);
  if (!privy.ready && !demo) return <div className="splash"><span className="brand-mark"><Zap size={20}/></span><p>Opening the market…</p></div>;
  if (!authenticated) return <Welcome onLogin={privy.login}/>;
  if (!token || !profile) return <div className="splash"><span className="brand-mark"><Zap size={20}/></span><p>Preparing your account…</p></div>;
  if (!profile.profileComplete) return <Onboarding profile={profile} token={token} onComplete={setProfile} onLogout={privy.logout}/>;
  return <div className="app-shell">
    <header><a className="brand" href="#"><span className="brand-mark"><Zap size={17}/></span><span>KRAFT/<b>TRADE</b></span></a><div className="header-right"><div className={`connection ${market.connected ? "online" : ""}`}><i/><span>{market.connected ? "Markets live" : "Connecting"}</span></div><div className="demo-pill">Paper funds</div><button className="icon-button" onClick={() => demo ? location.reload() : privy.logout()} aria-label="Log out"><LogOut size={17}/></button></div></header>
    <main>
      <section className="topline"><div><p className="eyebrow">Portfolio overview</p><h1>${money(portfolioValue(portfolio, market.tickers))}</h1><p className="muted">Total paper portfolio value</p></div><div className="balance"><WalletCards size={18}/><div><span>Available to trade</span><strong>${money(portfolio?.wallet.cashBalance ?? 0)} <small>USDT</small></strong></div></div></section>
      <section className="market-strip" aria-label="Markets">{MARKETS.map(symbol => { const t = market.tickers[symbol], up = Number(t?.changePercent) >= 0; return <button key={symbol} className={selected === symbol ? "market-chip active" : "market-chip"} onClick={() => setSelected(symbol)}><span><i>{short(symbol)}</i>/USDT</span><strong>{t ? `$${money(t.price, Number(t.price) < 1 ? 4 : 2)}` : "—"}</strong><em className={up ? "positive" : "negative"}>{t ? `${up ? "+" : ""}${money(t.changePercent)}%` : "Syncing"}</em></button>; })}</section>
      <section className="workspace">
        <div className="primary-panel">
          <div className="panel-head"><div><button className="symbol-select">{short(selected)} / USDT <ChevronDown size={16}/></button><div className="live-price"><strong>${market.tickers[selected] ? money(market.tickers[selected]!.price, Number(market.tickers[selected]!.price) < 1 ? 4 : 2) : "—"}</strong><span className={Number(market.tickers[selected]?.changePercent) >= 0 ? "positive" : "negative"}>{market.tickers[selected]?.changePercent ? `${Number(market.tickers[selected]?.changePercent) >= 0 ? "+" : ""}${money(market.tickers[selected]!.changePercent)}% today` : "Waiting for quote"}</span></div></div><div className="market-stats"><span>24h high <b>${money(market.tickers[selected]?.high ?? 0)}</b></span><span>24h low <b>${money(market.tickers[selected]?.low ?? 0)}</b></span><span>Volume <b>${compact(market.tickers[selected]?.volume)}</b></span></div></div>
          <Chart candles={candles}/><div className="chart-foot"><span>1M</span><span>LIVE · BINANCE</span></div>
        </div>
        <OrderBook symbol={selected} depth={market.depth}/>
        <TradeTicket symbol={selected} price={market.tickers[selected]?.price} connected={market.connected} portfolio={portfolio} token={token!} onExecuted={(trade, p) => { setPortfolio(p); setTrades(old => mergeTrade(old, trade)); refreshBonusData(); }} onConditional={order => { setOrders(old => [order, ...old]); refreshBonusData(); }}/>
      </section>
      <section className="lower-grid"><Holdings portfolio={portfolio} tickers={market.tickers}/><History trades={trades}/></section>
      <section className="bonus-grid"><PendingOrders orders={orders} token={token!} onCanceled={order => setOrders(old => old.map(o => o.id === order.id ? order : o))}/><Leaderboard entries={leaders}/></section>
    </main><footer><span>Market data provided by Binance</span><span>Simulation only · No real assets</span></footer>
  </div>;
}

function Welcome({ onLogin }: { onLogin: () => void }) { return <div className="welcome"><nav><div className="brand"><span className="brand-mark"><Zap size={17}/></span><span>KRAFT/<b>TRADE</b></span></div><button className="text-button" onClick={onLogin}>Sign in</button></nav><div className="hero"><p className="eyebrow"><Radio size={13}/> Real-time paper trading</p><h1>Learn the market.<br/><em>Risk nothing.</em></h1><p>Trade six leading cryptocurrencies against live Binance prices. A professional terminal, built for practice.</p><button className="cta" onClick={onLogin}>Open your free account <ArrowUpRight size={18}/></button><div className="hero-tape"><span>BTC / USDT</span><i>LIVE</i><span>ETH / USDT</span><i>LIVE</i><span>SOL / USDT</span></div></div><div className="welcome-note"><span>01</span><p>$10,000 in paper funds<br/>No card. No crypto wallet.</p></div></div>; }

function Onboarding({ profile, token, onComplete, onLogout }: { profile: UserProfile; token: string; onComplete: (profile: UserProfile) => void; onLogout: () => Promise<void> }) { const [name,setName]=useState(""),[saving,setSaving]=useState(false); async function submit(event:FormEvent){ event.preventDefault(); setSaving(true); try { const result=await saveProfile(token,{name}); onComplete(result.user); toast.success(`Welcome, ${result.user.name}`); } catch(e){ toast.error(e instanceof Error?e.message:"Could not save your profile"); } finally{setSaving(false);} } return <div className="onboarding"><nav><div className="brand"><span className="brand-mark"><Zap size={17}/></span><span>KRAFT/<b>TRADE</b></span></div><button className="text-button" onClick={onLogout}>Use another account</button></nav><form onSubmit={submit}><p className="eyebrow">One last detail</p><h1>What should we<br/>call you?</h1><p>Your name appears on your private account and the paper-trading leaderboard.</p><label>Full name<div className="input-wrap"><input autoFocus autoComplete="name" value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={60} placeholder="Your name"/></div></label><label>Verified email<div className="input-wrap readonly"><input value={profile.email ?? "No verified email found"} readOnly/><span>PRIVY</span></div></label><button className="cta" disabled={saving||name.trim().length<2}>{saving?"Creating account…":"Enter the market"}<ArrowUpRight size={18}/></button><small>Your email is verified by Privy and cannot be changed here.</small></form></div>; }

function TradeTicket({ symbol, price, connected, portfolio, token, onExecuted, onConditional }: { symbol: MarketSymbol; price?: string; connected: boolean; portfolio?: PortfolioView; token: string; onExecuted: (t: TradeView, p: PortfolioView) => void; onConditional: (o: OrderView) => void }) {
  const [side, setSide] = useState<"BUY"|"SELL">("BUY"), [type, setType] = useState<"MARKET"|"LIMIT"|"STOP_LOSS">("MARKET"), [quantity, setQuantity] = useState(""), [trigger, setTrigger] = useState(""), [pending, setPending] = useState(false); const asset = short(symbol), effectivePrice = type === "MARKET" ? Number(price ?? 0) : Number(trigger), total = Number(quantity) * effectivePrice; const holding = portfolio?.holdings.find(h => h.asset === asset); const invalid = !connected || !price || !quantity || Number(quantity) <= 0 || (type !== "MARKET" && (!trigger || Number(trigger)<=0)) || pending;
  useEffect(() => { if (type === "STOP_LOSS") setSide("SELL"); }, [type]);
  async function submit() { setPending(true); try { if (type === "MARKET") { const r = await placeOrder(token, { symbol, side, quantity, clientOrderId: crypto.randomUUID() }); onExecuted(r.trade, r.portfolio); toast.success(`${side === "BUY" ? "Bought" : "Sold"} ${r.trade.quantity} ${asset} at $${money(r.trade.price)}`); } else { const r = await placeConditionalOrder(token, { symbol, side, type, quantity, triggerPrice: trigger, clientOrderId: crypto.randomUUID() }); onConditional(r.order); toast.success(`${type === "LIMIT" ? "Limit" : "Stop-loss"} order placed`); } setQuantity(""); } catch(e) { toast.error(e instanceof Error ? e.message : "Order rejected"); } finally { setPending(false); } }
  return <aside className="trade-ticket"><div className="tabs"><button className={side === "BUY" ? "active" : ""} disabled={type === "STOP_LOSS"} onClick={() => setSide("BUY")}>Buy</button><button className={side === "SELL" ? "active sell" : ""} onClick={() => setSide("SELL")}>Sell</button></div><div className="ticket-body"><div className="order-types">{(["MARKET","LIMIT","STOP_LOSS"] as const).map(value => <button key={value} className={type===value?"active":""} onClick={() => setType(value)}>{value === "STOP_LOSS" ? "Stop" : value[0]+value.slice(1).toLowerCase()}</button>)}</div><p className="available">Available <b>{side === "BUY" ? `${money(portfolio?.wallet.cashBalance ?? 0)} USDT` : `${holding?.quantity ?? "0"} ${asset}`}</b></p><label>Quantity<div className="input-wrap"><input value={quantity} onChange={e => setQuantity(e.target.value)} inputMode="decimal" placeholder="0.00" aria-label="Order quantity"/><span>{asset}</span></div></label>{type !== "MARKET" && <label className="trigger-label">{type === "LIMIT" ? "Limit price" : "Stop price"}<div className="input-wrap"><input value={trigger} onChange={e => setTrigger(e.target.value)} inputMode="decimal" placeholder={price ?? "0.00"} aria-label="Trigger price"/><span>USDT</span></div></label>}<div className="quick-row">{[25,50,75,100].map(p => <button key={p} onClick={() => { const max = side === "BUY" ? Number(portfolio?.wallet.cashBalance ?? 0) / Number(effectivePrice || price || 1) : Number(holding?.quantity ?? 0); setQuantity((max * p / 100).toFixed(8).replace(/\.?0+$/, "")); }}>{p}%</button>)}</div><div className="order-summary"><span>Live price <b>{price ? `$${money(price, Number(price)<1?4:2)}` : "—"}</b></span><span>Estimated total <b>${money(total)}</b></span><span>Fee <b>$0.00</b></span></div><button className={`trade-button ${side === "SELL" ? "sell" : ""}`} disabled={invalid} onClick={submit}>{pending ? "Submitting…" : type === "MARKET" ? `${side === "BUY" ? "Buy" : "Sell"} ${asset}` : `Place ${type === "LIMIT" ? "limit" : "stop-loss"}`} <ArrowUpRight size={17}/></button><p className="execution-note">{type === "MARKET" ? "Executes instantly at the latest live quote." : "Monitored and executed server-side against live prices."}</p></div></aside>;
}

function OrderBook({ symbol, depth }: { symbol: MarketSymbol; depth?: { symbol: MarketSymbol; bids: [string,string][]; asks: [string,string][] } }) { const rows = depth?.symbol === symbol ? depth : undefined; return <aside className="orderbook"><div className="section-title"><h2>Order book</h2><span>0.01</span></div><div className="book-head"><span>Price</span><span>Amount ({short(symbol)})</span></div><div className="book asks">{(rows?.asks.slice(0,7).reverse() ?? []).map(([p,q]) => <div key={p}><span>{money(p, Number(p)<1?4:2)}</span><span>{money(q,4)}</span></div>)}</div><div className="spread"><b>${rows ? money((Number(rows.asks[0]?.[0])+Number(rows.bids[0]?.[0]))/2, Number(rows.asks[0]?.[0])<1?4:2) : "—"}</b><span>Mid price</span></div><div className="book bids">{(rows?.bids.slice(0,7) ?? []).map(([p,q]) => <div key={p}><span>{money(p, Number(p)<1?4:2)}</span><span>{money(q,4)}</span></div>)}</div>{!rows && <div className="book-loading">Streaming depth…</div>}</aside>; }

function Holdings({ portfolio, tickers }: { portfolio?: PortfolioView; tickers: ReturnType<typeof useMarket>["tickers"] }) { return <section className="data-panel"><div className="section-title"><h2>Your holdings</h2><span>{portfolio?.holdings.length ?? 0} assets</span></div><div className="holding-list">{portfolio?.holdings.length ? portfolio.holdings.map(h => { const ticker = tickers[`${h.asset}USDT` as MarketSymbol], value = Number(h.quantity) * Number(ticker?.price ?? 0), pnl = value - Number(h.quantity) * Number(h.averageCost); return <div className="holding-row" key={h.asset}><div className="coin-avatar">{h.asset.slice(0,1)}</div><div><strong>{h.asset}</strong><span>{ASSET_NAMES[`${h.asset}USDT` as MarketSymbol]}</span></div><div><strong>{h.quantity}</strong><span>Avg. ${money(h.averageCost)}</span></div><div><strong>${money(value)}</strong><span className={pnl >= 0 ? "positive" : "negative"}>{pnl >= 0 ? "+" : ""}${money(pnl)}</span></div></div>; }) : <Empty text="Your first trade will appear here."/>}</div></section>; }
function History({ trades }: { trades: TradeView[] }) { return <section className="data-panel"><div className="section-title"><h2>Recent activity</h2><span>Last 25 trades</span></div><div className="history-list">{trades.length ? trades.map(t => <div className="history-row" key={t.id}><span className={`type-icon ${t.side.toLowerCase()}`}>{t.side === "BUY" ? <ArrowDownLeft/> : <ArrowUpRight/>}</span><div><strong>{t.side === "BUY" ? "Bought" : "Sold"} {short(t.symbol)}</strong><span>{new Date(t.executedAt).toLocaleString()}</span></div><div><strong>{t.quantity} {short(t.symbol)}</strong><span>${money(t.quoteAmount)} at ${money(t.price)}</span></div></div>) : <Empty text="No trades yet. The market is waiting."/>}</div></section>; }
function PendingOrders({ orders, token, onCanceled }: { orders: OrderView[]; token: string; onCanceled: (order: OrderView) => void }) { const pending = orders.filter(o => o.status === "PENDING"); async function cancel(id:string){ try { const result=await cancelPendingOrder(token,id); onCanceled(result.order); toast.success("Order canceled"); } catch(e){ toast.error(e instanceof Error?e.message:"Could not cancel order"); } } return <section className="data-panel"><div className="section-title"><h2>Open orders</h2><span>{pending.length} pending</span></div><div className="pending-list">{pending.length ? pending.map(o => <div className="pending-row" key={o.id}><div><strong>{o.type === "STOP_LOSS" ? "Stop-loss" : "Limit"} · {o.side}</strong><span>{short(o.symbol)} / USDT</span></div><div><strong>{o.quantity} {short(o.symbol)}</strong><span>Trigger ${money(o.triggerPrice ?? 0, Number(o.triggerPrice)<1?4:2)}</span></div><button onClick={()=>cancel(o.id)}>Cancel</button></div>) : <Empty text="No conditional orders waiting."/>}</div></section>; }
function Leaderboard({ entries }: { entries: LeaderboardEntry[] }) { return <section className="data-panel"><div className="section-title"><h2>Top performers</h2><span>Paper returns</span></div><div className="leader-list">{entries.length ? entries.slice(0,8).map(e => <div className={`leader-row ${e.isCurrentUser?"you":""}`} key={e.rank}><b>#{e.rank}</b><div><strong>{e.alias}{e.isCurrentUser?" · You":""}</strong><span>${money(e.portfolioValue)} portfolio</span></div><em className={Number(e.returnPercent)>=0?"positive":"negative"}>{Number(e.returnPercent)>=0?"+":""}{e.returnPercent}%</em></div>) : <Empty text="Complete a trade to join the board."/>}</div></section>; }
function Empty({ text }: { text: string }) { return <div className="empty"><span>—</span><p>{text}</p></div>; }
function compact(value?: string) { if (!value) return "—"; return Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 }).format(Number(value)); }
function portfolioValue(portfolio?: PortfolioView, tickers?: ReturnType<typeof useMarket>["tickers"]) { return Number(portfolio?.wallet.cashBalance ?? 0) + (portfolio?.holdings ?? []).reduce((sum,h) => sum + Number(h.quantity)*Number(tickers?.[`${h.asset}USDT` as MarketSymbol]?.price ?? 0),0); }
